### PR TITLE
Improve server count post and other stuff

### PR DESCRIPTION
**Pull request by davidcralph**
See changes for info. You don't need to copy and paste the server count code repeatedly!

### CODE REVIEW

**Comment by davidcralph** [comment]
also improved readme uwu

**Comment by AutumnRivers** [comment]
Thank you very much for opening a pull request! I'll look into this soon.

**Comment by AutumnRivers** [comment]
Alright, well, this looks great. But it completely forgets to update DiscordBots stats. It only updates Terminal stats. I'll be denying this pull request, but feel free to make another one!

**Comment by AutumnRivers** [comment]
Actually wait nevermind I pasted that in my code wrong

**Pull request merged**
